apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-test
spec:
  selector:
    matchLabels:
      app: probes-test
  template:
    metadata:
      labels:
        app: probes-test
    spec:
      containers:
        - name: probes
          image: alexgraff/probes
          command:
            - python
          args:
            - /main.py
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              port: 8000
              path: /readiness
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              port: 8000
              path: /liveness
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              port: 8000
              path: /startup
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          env:
            - name: STARTUP
              value: "0"
            - name: READINESS
              value: "0"
            - name: LIVENESS
              value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: probes-test
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: probes-test



